name: cek_ongkir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_search: ^5.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/images/icon_launcher.png"

flutter:
  uses-material-design: true
